### ISSUE TITLE
Option for multiple domains

### ISSUE THREAD

**Issue by caillou** [joshuamorris3/namecheap-ddns-update#7]
We have successfully  been using your docker container to update the DNS entries to our self-hosted family server.

Currently we run multiple containers to update the different DNS entries on the server.

Would it be possible to extend the script to update multiple domains and subdomains in a sinlge container?

**Comment by joshuamorris3** [comment]
Glad to hear that it's been working for you. I'll look into allowing
multiple domains with multiple subdomains. Would a configuration file still
work in your setup, or do you need to use environment variables?

**Comment by caillou** [comment]
Thanks for your answer!

I thought about using a CNAME instead of updating the different domains, but this does not seem to be possible without a sub-domain, c.f. https://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain

I don’t mind how the config is passed. I feel that, if you actually spend time on this, it would make sense that it could be used with the `cli`. If the feature is not necessary enough for the `cli`, it is not really needed for the Docker container. And to be honest, there is no problem in running 2-3 Docker containers instead of one. Up to you!

This being said, we could go for a `EXTRA_DOMAINS` parameter in the `cli`, the way it is done here: https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md

I think the `EXTRA_DOMAINS` was added after the fact on the `letsencrypt` Docker image, and in order to stay backwards compatible:

```
-e URL=example.com \
-e ONLY_SUBDOMAINS=false \
-e SUBDOMAINS=www,mail,nextclound \
-e EXTRA_DOMAINS=foo.com,www.foo.com,bar.com \
```

**Comment by joshuamorris3** [comment]
@caillou take a look at the #8 PR and let me know if that works, apologies for the delay.

**Comment by caillou** [comment]
PR #8 would solve the issue. I close this issue, as the discussion continues there.

@joshuamorris3 thank you for the effort and there is no reason for an apology on your side!
