### ISSUE TITLE
Handling multiple domains

### ISSUE THREAD

**Issue by the-ebdm** [joshuamorris3/namecheap-ddns-update#9]
Hi, would it be possible to handle multiple domains with a single container? I'm currently spinning up one for each domain but it seems like a waste of resources. I'm happy to develop this feature

**Comment by joshuamorris3** [comment]
Hi @101stArrow does #8 do what you are looking for?

**Comment by the-ebdm** [comment]
@joshuamorris3 Yes it does indeed thanks for that. I hadn't actually noticed that before... Ah it's in the PRs tab - I use Bitbucket at work and so on the rare occasion I'm on here I get a little confused by the interface (irony being a UI/UX dev)
